name: Deployer

on:
  workflow_run:
    workflows: ["Builder"] #Nome do builder.yml
    types:
      - completed #Caso complete

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: Deploy

    steps:
      - name: Definir user e chave com base no auto
        id: setvars
        run: |
          AUTHOR="${{ github.event.workflow_run.head_commit.author.email }}"
          echo "Autor do push: $AUTHOR"

          if [[ "$AUTHOR" == "marioatccosta@gmail.com" ]]; then
            echo "ssh_user=${{ secrets.SSH_USER_DEV1 }}" >> $GITHUB_OUTPUT
            echo "ssh_key=${{ secrets.SSH_KEY_DEV1 }}" >> $GITHUB_OUTPUT
          elif [[ "$AUTHOR" == "dev2@example.com" ]]; then
            echo "ssh_user=${{ secrets.SSH_USER_DEV2 }}" >> $GITHUB_OUTPUT
            echo "ssh_key=${{ secrets.SSH_KEY_DEV2 }}" >> $GITHUB_OUTPUT
          elif [[ "$AUTHOR" == "dev3@example.com" ]]; then
            echo "ssh_user=${{ secrets.SSH_USER_DEV3 }}" >> $GITHUB_OUTPUT
            echo "ssh_key=${{ secrets.SSH_KEY_DEV3 }}" >> $GITHUB_OUTPUT
          else
            echo "Autor desconhecido. Falhando deploy."
            exit 1
          fi

      - name: Copiar docker-compose para o servidor
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ steps.setvars.outputs.ssh_user }}
          password: ${{ steps.setvars.outputs.ssh_pass }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml"
          target: "abay-api-app"

      - name: SSH e Pull
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ steps.setvars.outputs.ssh_user }}
          password: ${{ steps.setvars.outputs.ssh_pass }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            echo "Deploy feito com sucesso por ${{ steps.setvars.outputs.ssh_user }}"
            cd abay-api-app
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans