name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Teste Listar conteúdos da pasta
        run: ls -l

      - name: Make scripts executable
        run: |
          chmod +x ci/01-build.sh
          chmod +x ci/02-test.sh
          chmod +x ci/03-build-image.sh
          chmod +x ci/04-push-image.sh

      - name: Build app
        run: ./ci/01-build.sh

      - name: Run tests
        run: ./ci/02-test.sh

      - name: Build Docker image
        run: ./ci/03-build-image.sh

      - name: Push Docker image
        run: ./ci/04-push-image.sh
